<?php

$title = 'Task list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php // <-- Add this !!
echo $this->navigation('navigation')->menu();
?>

<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
</p>

<?php


$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
	<th>Due date</th>
	<th>Priority</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
	<td><?php echo $this->escapeHtml($album->due_date);?></td>
	<td><?php echo $this->escapeHtml($album->priority);?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php // add at the end of the file after the table
echo $this->paginationControl(
$this->paginator,
'Sliding',		
array('partial/paginator.phtml', 'Album'),
array(
'route' => 'album'
)
);
?>
